export const ENV = {
    API_BASE_URL: process.env.NEXT_PUBLIC_API_URL,
    SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    RAZORPAY_KEY: process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID
}
